# Generated by Django 4.2.6 on 2023-11-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fisioterapeuta',
            fields=[
                ('id_fisioterapeuta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.CharField(blank=True, max_length=10, null=True)),
                ('contra', models.CharField(max_length=20, unique=True)),
                ('fisioterapeutacol', models.CharField(db_column='Fisioterapeutacol', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostico_medico', models.TextField(blank=True, null=True)),
                ('fecha_inicio_terapia', models.DateField(blank=True, null=True)),
                ('plan_terapia', models.IntegerField(blank=True, null=True)),
                ('paciente_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('id_fisioterapeuta', models.ForeignKey(blank=True, db_column='id_fisioterapeuta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hand_care_assistant.fisioterapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id_terapia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('actividad_realizada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hand_care_assistant.paciente')),
            ],
        ),
    ]
