# Generated by Django 4.2.6 on 2023-11-02 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand_care_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisioterapeuta',
            name='fisioterapeutacol',
        ),
    ]
