# Generated by Django 4.2.6 on 2023-11-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_care_assistant', '0002_remove_fisioterapeuta_fisioterapeutacol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico_medico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico médico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_inicio_terapia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de terapia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='plan_terapia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plan de terapia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número telefónico'),
        ),
    ]
