# Generated by Django 4.2.6 on 2023-11-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_care_assistant', '0003_alter_paciente_apellido_alter_paciente_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
