# Generated by Django 4.2.6 on 2023-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_care_assistant', '0007_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='fecha_hora_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terapia',
            name='fecha_hora_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
